name: 'Update image running in tcm'
inputs:
  repoName:
    required: true
  tcmKey:
    required: true
  tcmAddr:
    required: true
  imageTag:
    required: false
    default: ""
runs:
  using: composite
  steps:
    - run: ${{github.action_path}}/update_tcm.sh
      shell: bash
      env:
        REPO_NAME: ${{inputs.repoName}}
        TCM_KEY: ${{inputs.tcmKey}}
        TCM_ADDR: ${{inputs.tcmAddr}}
        GCR_REPO: gcr.io/kubernetes-221218
        IMAGE_TAG: ${{inputs.imageTag}}
