name: 'Build docker image and push to AWS ECR'
inputs:
  repoName:
    required: true
  version:
    required: true
  awsAccountId:
    required: false
    default: "885847356140"
  awsRegion:
    required: false
    default: us-east-2
outputs:
  tag:
    value: ${{steps.push.outputs.tag}}
runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{inputs.awsAccountId}}:role/${{inputs.repoName}}-deployer
        aws-region: ${{inputs.awsRegion}}
    - uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr
    - run: aws sts get-caller-identity
      shell: bash
    - run: ${{ github.action_path }}/push_image_to_ecr.sh
      id: push
      shell: bash
      env:
        REPO_NAME: ${{inputs.repoName}}
        ECR_REPO: ${{steps.login-ecr.outputs.registry}}
        VERSION: ${{inputs.version}}
