name: 'Build docker image'
inputs:
  repoName:
    required: true
outputs:
  version:
    value: ${{steps.build.outputs.version}}
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/build_image.sh
      id: build
      shell: bash
      env:
        REPO_NAME: ${{inputs.repoName}}
