name: 'Build docker image'
inputs:
  repoName:
    required: true
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/build_image.sh
      shell: bash
      env:
        REPO_NAME: ${{inputs.repoName}}
