name: 'Build docker image and push to gcr'
inputs:
  repoName:
    required: true
  serviceAccount:
    required: true
outputs:
  tag:
    value: ${{steps.push.outputs.tag}}
runs:
  using: composite
  steps:
    - uses: tanelso2/deployment_scripts/actions/install_gcloud@main
    - run: echo "${GCR_SERVICE_ACCOUNT}" > service-account.json
      shell: bash
      env:
        GCR_SERVICE_ACCOUNT: ${{inputs.serviceAccount}}
    - run: ${{ github.action_path }}/push_image_to_gcr.sh
      shell: bash
      id: push
      env:
        CLOUDSDK_CORE_DISABLE_PROMPTS: '1'
        REPO_NAME: ${{inputs.repoName}}
        GCR_REPO: gcr.io/kubernetes-221218
